# Замените EXAMPLE на слаг вашей организации, а my-site — на имя репозитория.
baseURL = "https://zabivakaxd.sourcecraft.site/lab-1-sem-6/"
languageCode = "ru-ru"
title = "Мой сайт на Hugo"

[params]
  description = "Демо-сайт на Hugo, собранный и опубликованный через SourceCraft CI/CD"

[menu]
  [[menu.main]]
    name = "Главная"
    pageRef = "/"
    weight = 1
  [[menu.main]]
    name = "Записи"
    pageRef = "/posts"
    weight = 2
  [[menu.main]]
    name = "Обо мне"
    pageRef = "/about"
    weight = 3

# Разрешаем inline-HTML внутри Markdown (полезно для Hugo-контента)
[markup.goldmark.renderer]
  unsafe = true
